"use client";

import { useState, useRef, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Upload, ArrowUp, SearchIcon, User, Bot, Copy, RefreshCcw, ThumbsUp, ThumbsDown } from "lucide-react";
import { API_BASE_URL } from "@/app/constant/constant";

export default function ChatInterface({ darkMode }) {
  const [msg, setMsg] = useState("");
  const [messages, setMessages] = useState([]);
  const [started, setStarted] = useState(false);
  const [loading, setLoading] = useState(false);

  const scrollRef = useRef(null);

  // AUTO SCROLL
  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages, loading]);

  const suggestions = [
    "How can I organize documents within the system?",
    "How do I search for a specific document?",
    "How do I upload documents to the DMS?",
  ];

  const sendMessage = async () => {
    if (!msg.trim()) return;

    if (!started) setStarted(true);

    // USER MESSAGE
    const userMsg = { role: "user", content: msg.trim() };
    const newMessages = [...messages, userMsg]; // ← FIX: use local updated array
    setMessages(newMessages);
    setMsg("");

    // LOADING MESSAGE
    const loadingMsg = {
      role: "assistant",
      content: "AI is typing...",
      loading: true,
    };

    setMessages([...newMessages, loadingMsg]);
    setLoading(true);

    try {
      const res = await fetch(`${API_BASE_URL}/gemini`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: userMsg.content }),
      });

      const data = await res.json();
      const aiText = data.text || "No response";

      // REPLACE LOADING MESSAGE WITH REAL REPLY
      setMessages((prev) =>
        prev.map((m) =>
          m.loading
            ? { role: "assistant", content: aiText }
            : m
        )
      );
    } catch (err) {
      setMessages((prev) =>
        prev.map((m) =>
          m.loading
            ? { role: "assistant", content: "Server error." }
            : m
        )
      );
    }

    setLoading(false);
  };

  const handleKey = (e) => {
    if (e.key === "Enter") sendMessage();
  };

  return (
    <div
      className={`flex flex-col items-center w-full h-full transition-all duration-500 ${started ? "justify-end pb-6" : "justify-center"
        }`}
    >
      {!started && (
        <>
          <h1
            className={`text-4xl font-semibold ${darkMode ? "text-white" : "text-gray-900"
              }`}
          >
            Meet AI Mode
          </h1>

          <p
            className={`text-xl mt-1 ${darkMode ? "text-gray-300" : "text-gray-700"
              }`}
          >
            Ask detailed questions for better responses
          </p>
        </>
      )}
      {started && (
        <div
          ref={scrollRef}
          className="w-[650px] h-[65vh] overflow-y-auto mb-6 space-y-2 pr-2 flex flex-col"
        >
          {messages.map((m, i) => (
            <div
              key={i}
              className={`
          flex items-start gap-2 max-w-[70%] 
          ${m.role === "user" ? "self-end flex-row-reverse" : "self-start"}
        `}
            >


              {/* Message Bubble */}
              <div className="flex flex-col relative">
                <div
                  className={`
              py-3 px-5 wrap-break-words rounded-tr-full rounded-tl-full rounded-bl-full
              ${darkMode ? "text-gray-300" : " text-gray-800"}
              ${m.role === "user" ? "bg-gray-800 text-white" : "bg-transparent"}
            `}
                >
                  {m.content}
                </div>

                {/* AI footer: copy + generated by */}
                {m.role === "assistant" && (
                  <div className="flex justify-between mt-1 text-xs text-gray-500 px-6 ">
                    <button
                      className="flex items-center gap-4 hover:text-gray-700"
                      onClick={() => navigator.clipboard.writeText(m.content)}
                    >
                      <Copy className="h-3 w-3" />
                      <RefreshCcw className="h-3 w-3" />
                      <ThumbsUp className="h-3 w-3" />
                      <ThumbsDown className="h-3 w-3" />
                    </button>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      )}


      <div
        className={`w-[650px] mt-8 rounded-2xl border p-4 shadow-[0_0_60px_-12px_rgba(0,0,0,0.5)] transition ${darkMode
            ? "bg-[#1A1B1E] border-[#2A2A2D]"
            : "bg-gray-200 border-gray-400"
          }`}
      >
        <div className="flex items-center gap-3">
          <Input
            value={msg}
            onChange={(e) => setMsg(e.target.value)}
            onKeyDown={handleKey}
            placeholder="Message AI Mode"
            className={`flex-1 bg-transparent border-0 placeholder-gray-500 focus-visible:ring-0 ${darkMode ? "text-gray-200" : "text-gray-900"
              }`}
          />

          <button
            className={`p-2 rounded-full transition ${darkMode ? "hover:bg-[#2A2A2D]" : "hover:bg-gray-300"
              }`}
          >
            <Upload
              className={`h-5 w-5 ${darkMode ? "text-gray-300" : "text-gray-800"
                }`}
            />
          </button>

          <button
            onClick={sendMessage}
            className={`p-2 rounded-full transition ${darkMode
                ? "bg-white text-black hover:bg-[#1F4CD8]"
                : "bg-gray-800 hover:bg-[#1F4CD8]"
              }`}
          >
            <ArrowUp
              className={`${darkMode ? "text-black" : "text-white"} h-5 w-5`}
            />
          </button>
        </div>

        <div className="flex items-center gap-2 mt-4">
          <Button
            variant="outline"
            className={`rounded-full ${darkMode
                ? "border-[#2A2A2D] bg-[#1A1B1E] text-gray-300"
                : "border-gray-400 bg-gray-300 text-gray-900"
              }`}
          >
            ⨉ DeepThink
          </Button>

          <Button
            variant="outline"
            className={`rounded-full ${darkMode
                ? "border-[#2A2A2D] bg-[#1A1B1E] text-gray-300"
                : "border-gray-400 bg-gray-300 text-gray-900"
              }`}
          >
            🌐 Search
          </Button>
        </div>
      </div>

      {!started && (
        <div className="w-[650px] mt-4">
          {suggestions.map((item, i) => (
            <div
              key={i}
              className={`flex items-center gap-3 px-4 py-2 rounded-2xl cursor-pointer transition ${darkMode
                  ? "text-gray-300 hover:bg-[#1A1B1E]"
                  : "text-gray-800 hover:bg-gray-200"
                }`}
              onClick={() => {
                setMsg(item);
                setStarted(true);
              }}
            >
              <SearchIcon
                className={`h-4 w-4 ${darkMode ? "text-gray-300" : "text-gray-600"
                  }`}
              />
              {item}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
